# Auto-generated dynamic seeds. Do not edit manually.
from __future__ import annotations

DYNAMIC_SEEDS: dict[str, dict] = {'3092718637033': {'brand': 'Teisseire',
                   'description': 'Sirop Menthe  Verte TEISSEIRE',
                   'ean': '3092718637033',
                   'image': 'https://media.carrefour.fr/medias/011ef995a0f24adba2decbc518cc9ed7/p_540x540/03 '
                            '092718637033_C1N1_s03.png',
                   'leclerc_queries': ['Teisseire 60 CL',
                                       'Teisseire Sirop 60 CL',
                                       'Teisseire Sirop Menthe 60 CL',
                                       'Sirop Menthe 60 CL',
                                       'Teisseire Menthe 60 CL',
                                       'Teisseire Sirop Menthe Verte 60 CL',
                                       'Sirop Menthe Verte TEISSEIRE',
                                       '3092718637033'],
                   'leclerc_query': 'Teisseire 60 CL',
                   'name': 'Sirop Menthe  Verte TEISSEIRE',
                   'note': 'Collecte seed via carrefour_market',
                   'nutriscore_grade': 'c',
                   'nutriscore_image': 'https://www.coursesu.com/on/demandware.static/-/Sites-DigitalU-Library/default/ '
                                       'dw250d3832/pictos-navigation/nutrition_et_regimes_alimentaires.png',
                   'quantity': '60 CL',
                   'removed': False,
                   'seed_primary_name': 'Sirop Menthe  Verte TEISSEIRE',
                   'seed_primary_quantity': '60 CL',
                   'seed_query': 'Teisseire Sirop Menthe Verte 60 CL',
                   'source': 'carrefour_super'},
 '3174660031913': {'brand': 'Béghin Say',
                   'description': 'Sucre en poudre extra fin Béghin Say 1 kg',
                   'ean': '3174660031913',
                   'image': 'https://cdn.auchan.fr/media/A0219970930000360781PRIMARY_1200x1200/B2CD/',
                   'leclerc_queries': ['Beghin Say 1 KG',
                                       'Beghin Say Sucre 1 KG',
                                       'Beghin Say Sucre Poudre 1 KG',
                                       'Sucre Poudre 1 KG',
                                       'Sucre Poudre Extra Fin Béghin Say',
                                       '3174660031913'],
                   'leclerc_query': 'Beghin Say 1 KG',
                   'name': 'Sucre en poudre extra fin Béghin Say 1 kg',
                   'nutriscore_grade': 'e',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-e.svg',
                   'quantity': '1 KG',
                   'seed_primary_name': 'Sucre poudre extra fin Béghin Say',
                   'seed_primary_quantity': '1 KG',
                   'seed_query': 'Beghin Say sucre poudre extra fin 1 kg',
                   'source': 'carrefour_market'},
 '3665468000329': {'ean': '3665468000329',
                   'leclerc_queries': ['3665468000329'],
                   'leclerc_query': '3665468000329',
                   'note': '',
                   'removed': False,
                   'seed_query': '3665468000329',
                   'source': 'unknown'},
 '5411188119098': {'brand': 'Alpro',
                   'description': 'Dessert végétal soja nature à la noix de coco ALPRO',
                   'ean': '5411188119098',
                   'image': 'https://media.carrefour.fr/media/referential/media/d534d5010ea842138387e4c7910b '
                            '6b3e/05411188119098_H1N1_s14.png',
                   'leclerc_queries': ['Alpro 500 G',
                                       'Alpro Dessert 500 G',
                                       'Alpro Dessert végétal 500 G',
                                       'Dessert végétal 500 G',
                                       'Alpro végétal 500 G',
                                       'Alpro Dessert végétal soja nature noix coco 500 G',
                                       'Dessert végétal soja nature à la noix de coco ALPRO',
                                       '5411188119098'],
                   'leclerc_query': 'Alpro 500 G',
                   'name': 'Dessert végétal soja nature à la noix de coco ALPRO',
                   'note': 'Collecte seed via carrefour_market',
                   'nutriscore_grade': 'e',
                   'nutriscore_image': 'https://eu-images.contentstack.com/v3/assets/blta867006d326c1e47/bltfca4e212b35 '
                                       '0ee05/nutriscore-a',
                   'quantity': '500 G',
                   'removed': False,
                   'seed_primary_name': 'Dessert végétal soja nature à la noix de coco ALPRO',
                   'seed_primary_quantity': '500 G',
                   'seed_query': 'Alpro Dessert végétal soja nature noix coco 500 G',
                   'source': 'unknown'}}
