"""Seed catalog codé en dur (remplace l'ancien manual_descriptors.json)."""
from __future__ import annotations

SEED_CATALOG = {'1234567890123': {'ean': '1234567890123',
                   'leclerc_queries': ['1234567890123'],
                   'leclerc_query': '1234567890123',
                   'primary_keywords': ['1234567890123'],
                   'removed': True,
                   'source': 'auto'},
 '3017760821375': {'ean': '3017760821375',
                   'leclerc_queries': ['3017760821375'],
                   'leclerc_query': '3017760821375',
                   'primary_keywords': ['3017760821375'],
                   'removed': True,
                   'source': 'auto'},
 '3033491485756': {'brand': 'Hipro',
                   'canonical': {'brand': 'Hipro',
                                 'ean': '3033491485756',
                                 'features': [],
                                 'flavor_color': 'fraise',
                                 'form': 'boisson',
                                 'images': [],
                                 'line': None,
                                 'name_core': 'Yaourt a boire Hipro',
                                 'normalized_signature': '3033491485756 hipro yaourt a boire hipro '
                                                         'fraise 0.35l',
                                 'pack_count': None,
                                 'size_unit': 'l',
                                 'size_value': 0.35,
                                 'variant': 'fraise'},
                   'description': 'Yaourt à boire fraise framboise protéiné 0%mg HIPRO - 300g',
                   'ean': '3033491485756',
                   'image': './assets/3033491485756.jpg',
                   'leclerc_queries': ['Hipro 300 G',
                                       'Hipro Yaourt 300 G',
                                       'Hipro Yaourt boire 300 G',
                                       'Yaourt boire 300 G',
                                       'Hipro boire 300 G',
                                       'Hipro Yaourt boire fraise framboise protéiné mg 300 g',
                                       'Yaourt à boire fraise framboise protéiné 0% MG HIPRO',
                                       'Yaourt à boire fraise framboise protéiné 0%mg HIPRO - 300g',
                                       '3033491485756'],
                   'leclerc_query': 'Hipro 300 G',
                   'name': 'Yaourt à boire fraise framboise protéiné 0%mg HIPRO - 300g',
                   'negatives': {'monoprix': ['sans sucre', 'zero', 'light']},
                   'note': '2025-11-01T10:46:07Z · Monoprix auto',
                   'nutriscore_grade': 'unknown',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-unknown.svg',
                   'primary_keywords': ['Hipro 300 G'],
                   'quantity': '300  g',
                  'queries': {'monoprix': ['Hipro fraise',
                                           'Hipro fraise framboise',
                                           'Hipro framboise',
                                           'Hipro yaourt'],
                              'casino': ['hipro fraise',
                                         'hipro boisson 300g',
                                         'hipro yaourt boire']},
                  'courseu_url': 'https://www.coursesu.com/p/yaourt-a-boire-fraise-framboise-proteine-0mg-hipro---300g/3722232.html',
                  'secondary_keywords': ['boire',
                                          'fraise',
                                          'framboise',
                                          'protéiné',
                                          'MG',
                                          '300 G'],
                   'seed_primary_name': 'Yaourt à boire fraise framboise protéiné 0% MG HIPRO',
                   'seed_primary_quantity': '300 G',
                   'seed_query': 'Hipro Yaourt boire fraise framboise protéiné mg 300 g',
                   'source': 'courseu'},
 '3088545004001': {'allow_monoprix_squeeze': True,
                   'brand': 'Lune de Miel',
                   'canonical': {'brand': 'Miel',
                                 'ean': '3088545004001',
                                 'features': [],
                                 'flavor_color': None,
                                 'form': None,
                                 'images': ['./assets/3088545004001.jpg',
                                            'https://media.carrefour.fr/medias/d8aa6570317942179a0878c49b469cab/p_540x540/03 '
                                            '088545004001_A1L1_s01.png',
                                            'https://cdn.auchan.fr/media/A0220040608000060158PRIMARY_1200x1200/B2CD/'],
                                 'line': None,
                                 'name_core': 'de fleurs LUNE DE',
                                 'normalized_signature': '3088545004001 miel de fleurs lune de '
                                                         '500.0g',
                                 'pack_count': None,
                                 'size_unit': 'g',
                                 'size_value': 500.0,
                                 'variant': None},
                   'description': 'Miel de fleurs liquide LUNE DE MIEL, 500g',
                   'ean': '3088545004001',
                   'image': './assets/3088545004001.jpg',
                   'leclerc_queries': ['Miel 500 G',
                                       'Miel Fleurs 500 G',
                                       'Miel Fleurs Liquide 500 G',
                                       'Fleurs Liquide 500 G',
                                       'Miel Liquide 500 G',
                                       'Miel fleurs liquide LUNE 500 g',
                                       'Miel De Fleurs Liquide LUNE DE MIEL',
                                       'Miel de fleurs liquide LUNE DE MIEL, 500g',
                                       '3088545004001'],
                   'leclerc_query': 'Miel 500 G',
                   'name': 'Miel de fleurs liquide LUNE DE MIEL, 500g',
                   'negatives': {'intermarche': ['zero',
                                                 'light',
                                                 'vanille',
                                                 'cherry',
                                                 'sans sucre',
                                                 'zéro',
                                                 '500.5g',
                                                 '499.5g',
                                                 'promo',
                                                 'lot',
                                                 'x2',
                                                 'x3',
                                                 'mega'],
                                 'leclerc': ['zero',
                                             'light',
                                             'vanille',
                                             'cherry',
                                             'sans sucre',
                                             'zéro',
                                             '500.5g',
                                             '499.5g',
                                             'lot',
                                             'duo',
                                             'family',
                                             'ecopack'],
                                 'monoprix': ['zero',
                                              'light',
                                              'vanille',
                                              'cherry',
                                              'sans sucre',
                                              'zéro',
                                              '500.5g',
                                              '499.5g',
                                              'promo',
                                              'lot',
                                              'eco',
                                              'maxi',
                                              'format']},
                   'note': '2025-11-02T11:38:43Z · Super U Eysines',
                   'nutriscore_grade': 'unknown',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-unknown.svg',
                   'primary_keywords': ['Miel 500 G'],
                   'quantity': '500  g',
                   'queries': {'intermarche': ['miel 500g', 'miel fleurs 500g'],
                               'leclerc': ['miel fleurs', 'miel 500g'],
                               'monoprix': ['lune de miel', 'lune de miel fleurs'],
                               'casino': ['miel lune de miel 500g',
                                          'miel fleurs 500g',
                                          'miel squeeze 500g']},
                   'removed': False,
                   'secondary_keywords': ['Liquide', 'LUNE', '500 G', 'Squeeze'],
                   'seed_primary_name': 'Miel  De Fleurs Liquide LUNE DE MIEL',
                   'seed_primary_quantity': '500 G',
                   'seed_query': 'Miel fleurs liquide LUNE 500 g',
                   'source': 'courseu'},
 '3092718637033': {'auchan_url': 'https://www.auchan.fr/teisseire-sirop-de-menthe/pr-C1628583',
                   'brand': 'Teisseire',
                   'canonical': {'brand': 'Teisseire',
                                 'ean': '3092718637033',
                                 'features': [],
                                 'flavor_color': 'menthe',
                                 'form': 'sirop',
                                 'images': ['https://cdn.auchan.fr/media/S01000000028624PRIMARY_1200x1200/B2CD/'],
                                 'line': None,
                                 'name_core': 'Sirop menthe verte',
                                 'normalized_signature': '3092718637033 teisseire sirop menthe verte 0.6l',
                                 'pack_count': None,
                                 'size_unit': 'l',
                                 'size_value': 0.6,
                                 'variant': 'verte'},
                   'description': 'Sirop menthe verte TEISSEIRE – 60 CL',
                   'ean': '3092718637033',
                   'image': './assets/3092718637033.jpg',
                   'leclerc_queries': ['Sirop Menthe 60 CL',
                                       'Teisseire Menthe 60 CL',
                                       'Sirop Menthe Teisseire 60 CL',
                                       'Menthe Teisseire 60 CL',
                                       '3092718637033'],
                   'leclerc_query': 'Sirop Menthe 60 CL',
                   'name': 'Sirop menthe verte TEISSEIRE – 60 CL',
                   'primary_keywords': ['Sirop Menthe 60 CL'],
                   'quantity': '60 CL',
                   'seed_primary_name': 'Sirop menthe verte TEISSEIRE',
                   'seed_primary_quantity': '60 CL',
                   'seed_query': 'Sirop Menthe 60 CL',
                   'source': 'carrefour'},
 '3124480200433': {'auchan_slug': 'auchan-drive-supermarche-talence-gallieni',
                   'auchan_store_home_url': 'https://www.auchan.fr/magasins/drive/auchan-drive-supermarche-talence-gallieni/s-6117',
                   'auchan_store_label': 'Auchan Drive Supermarché Talence-Gallieni',
                   'auchan_store_switch_url': 'https://www.auchan.fr/s-6117',
                   'auchan_store_url': 'https://www.auchan.fr/magasins/drive/auchan-drive-supermarche-talence-gallieni/s-6117',
                   'auchan_url': 'https://www.auchan.fr/orangina-boisson-gazeuse-a-l-orange/pr-C1820950',
                   'brand': 'Orangina',
                   'canonical': {'brand': 'Orangina',
                                 'ean': '3124480200433',
                                 'features': [],
                                 'flavor_color': 'orange',
                                 'form': None,
                                 'images': ['./assets/3124480200433.jpg',
                                            'https://media.carrefour.fr/medias/ac4e9a8cea3f4ae28c64deecfc0cf116/p_540x540/03124480200433_C1N1_s04.jpeg',
                                            'https://cdn.auchan.fr/media/S010000000419TMPRIMARY_1200x1200/B2CD/'],
                                 'line': None,
                                 'name_core': "Boisson gazeuse à la pulpe d'orange  ORANGINA 1.5 L",
                                 'normalized_signature': '3124480200433 orangina boisson gazeuse a '
                                                         'la pulpe d orange orangina 1.5l 1.5l',
                                 'pack_count': None,
                                 'size_unit': 'l',
                                 'size_value': 1.5,
                                 'variant': None},
                   'categories': 'Beverages and beverages preparations, Plant-based foods and '
                                 'beverages, Beverages, Plant-based beverages, Carbonated drinks, '
                                 'Fruit-based beverages, Sodas, Fruit sodas, Orange soft drinks, '
                                 'en:sweetened-beverages',
                   'courseu_slug': '/p/soda-a-lorange-orangina---la-bouteille-de-15l/1992614.html',
                   'courseu_url': 'https://www.coursesu.com/p/soda-a-lorange-orangina---la-bouteille-de-15l/1992614.html',
                   'description': "Soda à  l'Orange et sa Pulpe ORANGINA",
                   'ean': '3124480200433',
                   'ecoscore_grade': 'not-applicable',
                   'ecoscore_image': None,
                   'image': 'https://media.carrefour.fr/medias/ac4e9a8cea3f4ae28c64deecfc0cf116/p_540x540/03124480200433_C1N1_s04.jpeg',
                   'leclerc_queries': ['Orangina 1.5 L',
                                       'Orangina Soda 1.5 L',
                                       'Orangina Soda Orange 1.5 L',
                                       'Soda Orange 1.5 L',
                                       'Orangina Orange 1.5 L',
                                       "Orangina Soda l'Orange sa Pulpe 1,5 L",
                                       "Soda à l'Orange et sa Pulpe ORANGINA",
                                       '3124480200433'],
                   'leclerc_query': 'Orangina 1.5 L',
                   'name': "Soda à  l'Orange et sa Pulpe ORANGINA",
                   'negatives': {'intermarche': ['2l', '1l', 'promo', 'lot', 'x2', 'x3', 'mega'],
                                 'leclerc': ['2l', '1l', 'lot', 'duo', 'family', 'ecopack'],
                                 'monoprix': ['2l', '1l', 'promo', 'lot', 'eco', 'maxi', 'format']},
                   'note': 'Collecte seed via carrefour_super',
                   'nova_group': '4',
                   'nutriscore_grade': 'e',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-e.svg',
                   'primary_keywords': ['Orangina 1.5 L'],
                   'quantity': '1,5 L',
                   'queries': {'intermarche': ['Orangina 1.5L'],
                               'leclerc': ['Orangina 1.5L'],
                               'monoprix': ['Orangina 1.5L'],
                               'casino': ['orangina 1.5l',
                                          "orangina soda 1,5 l",
                                          'orangina pulpe 1.5']},
                   'removed': False,
                   'secondary_keywords': ['Orange', 'sa', 'Pulpe', '1.5 L'],
                   'seed_primary_name': "Soda à  l'Orange et sa Pulpe ORANGINA",
                   'seed_primary_quantity': '1,5 L',
                   'seed_query': "Orangina Soda l'Orange sa Pulpe 1,5 L",
                   'source': 'carrefour_super'},
 '3222472129798': {'ean': '3222472129798',
                   'leclerc_queries': ['3222472129798'],
                   'leclerc_query': '3222472129798',
                   'primary_keywords': ['3222472129798'],
                   'removed': True,
                   'source': 'auto'},
 '3274080005003': {'ean': '3274080005003',
                   'leclerc_queries': ['3274080005003'],
                   'leclerc_query': '3274080005003',
                   'primary_keywords': ['3274080005003'],
                   'removed': True,
                   'source': 'auto'},
 '3599741007593': {'ean': '3599741007593',
                   'leclerc_queries': ['3599741007593'],
                   'leclerc_query': '3599741007593',
                   'primary_keywords': ['3599741007593'],
                   'removed': True,
                   'source': 'auto'},
 '3665468000312': {'brand': 'Destop',
                   'courseu_slug': '/p/deboucheur-liquide-destop-flacon-950ml/3867435.html',
                   'courseu_url': 'https://www.coursesu.com/p/deboucheur-liquide-destop-flacon-950ml/3867435.html',
                   'description': 'Déboucheur liquide destop flacon 950ml',
                   'ean': '3665468000312',
                   'image': './assets/3665468000312.jpg',
                   'leclerc_queries': ['Destop 950 ML',
                                       'Destop Déboucheur 950 ML',
                                       'Destop Déboucheur Liquide 950 ML',
                                       'Déboucheur Liquide 950 ML',
                                       'Destop Liquide 950 ML',
                                       'Destop Déboucheur liquide flacon 950 ml',
                                       'Déboucheur Liquide Multi-Usages DESTOP',
                                       'Déboucheur liquide destop flacon 950ml',
                                       '3665468000312'],
                   'leclerc_query': 'Destop 950 ML',
                   'name': 'Déboucheur liquide destop flacon 950ml',
                   'note': '2025-11-01T11:32:40Z · Monoprix auto',
                   'nutriscore_grade': 'unknown',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-unknown.svg',
                   'primary_keywords': ['Destop 950 ML'],
                   'quantity': '950 ml',
                   'queries': {'monoprix': ['Destop déboucheur 950 ml',
                                            'Destop liquide 950 ml',
                                            'Destop deboucheur'],
                               'casino': ['destop 950 ml',
                                          'destop deboucheur 950',
                                          'deboucheur liquide destop']},
                   'removed': False,
                   'secondary_keywords': ['Liquide', 'Multi', 'Usages', 'flacon', '950 ML'],
                   'seed_primary_name': 'Déboucheur Liquide Multi-Usages DESTOP',
                   'seed_primary_quantity': '950 ML',
                   'seed_query': 'Destop Déboucheur liquide flacon 950 ml',
                   'source': 'courseu'},
'3174660031913': {'brand': 'Béghin Say',
                  'description': 'Sucre en poudre extra fin Béghin Say 1 kg',
                  'ean': '3174660031913',
                  'image': 'https://cdn.auchan.fr/media/A0219970930000360781PRIMARY_1200x1200/B2CD/',
                  'leclerc_queries': ['Beghin Say 1 KG',
                                      'Beghin Say Sucre 1 KG',
                                      'Beghin Say Sucre Poudre 1 KG',
                                      'Sucre Poudre 1 KG',
                                      'Sucre Poudre Extra Fin Béghin Say',
                                      '3174660031913'],
                  'leclerc_query': 'Beghin Say 1 KG',
                  'name': 'Sucre en poudre extra fin Béghin Say 1 kg',
                  'nutriscore_grade': 'e',
                  'nutriscore_image': '../assets/nutriscore/nutriscore-e.svg',
                  'primary_keywords': ['Beghin Say 1 KG'],
                  'quantity': '1 KG',
                  'seed_primary_name': 'Sucre poudre extra fin Béghin Say',
                  'seed_primary_quantity': '1 KG',
                  'seed_query': 'Beghin Say sucre poudre extra fin 1 kg',
                  'source': 'carrefour_market'},
'3665468000329': {'brand': 'Destop',
                  'description': 'Déboucheur express gel multi-usages Destop 950ml',
                  'ean': '3665468000329',
                  'image': './assets/3665468000329.jpg',
                  'leclerc_queries': ['Destop gel 950 ML',
                                      'Destop Express 950 ML',
                                      'Destop Déboucheur gel 950 ML',
                                      'Déboucheur gel 950 ML',
                                      'Destop gel multi usages',
                                      '3665468000329'],
                  'leclerc_query': 'Destop gel 950 ML',
                  'name': 'Déboucheur express gel multi-usages Destop 950ml',
                  'note': '2025-11-14T12:15:00Z · Carrefour seed',
                  'nutriscore_grade': 'unknown',
                  'nutriscore_image': '../assets/nutriscore/nutriscore-unknown.svg',
                  'primary_keywords': ['Destop gel 950 ML'],
                  'quantity': '950 ml',
                  'queries': {'monoprix': ['Destop express 950 ml',
                                           'Destop deboucheur gel 950 ml',
                                           'Destop gel multi usages'],
                              'casino': ['destop gel 950 ml',
                                         'destop express 950',
                                         'deboucheur gel destop']},
                  'removed': False,
                  'secondary_keywords': ['Gel', 'Express', 'Multi', 'Usages', '950 ML'],
                  'seed_primary_name': 'Déboucheur Express Gel Multi-Usages DESTOP',
                  'seed_primary_quantity': '950 ML',
                  'seed_query': 'Destop gel express 950 ml',
                  'source': 'carrefour_market'},
 '3665468402529': {'ean': '3665468402529',
                   'leclerc_queries': ['3665468402529'],
                   'leclerc_query': '3665468402529',
                   'primary_keywords': ['3665468402529'],
                   'removed': True,
                   'source': 'auto'},
 '5000112611861': {'brand': 'Cola',
                   'canonical': {'brand': 'Coca-Cola',
                                 'ean': '5000112611861',
                                 'features': [],
                                 'flavor_color': 'cola',
                                 'form': None,
                                 'images': ['./assets/5000112611861.jpg',
                                            'https://media.carrefour.fr/medias/ae537bba4fd64333b73d2226158bb23c/p_540x540/05 '
                                            '000112611861_H1N1_s01.png',
                                            'https://cdn.auchan.fr/media/A0220180604000507216PRIMARY_1200x1200/B2CD/'],
                                 'line': None,
                                 'name_core': 'Boisson gazeuse aux extraits',
                                 'normalized_signature': '5000112611861 coca cola boisson gazeuse '
                                                         'aux extraits original 1.75l',
                                 'pack_count': None,
                                 'size_unit': 'l',
                                 'size_value': 1.75,
                                 'variant': 'original'},
                   'courseu_slug': '/p/soda-coca-cola-original---bouteille-175l/5192990.html',
                   'courseu_url': 'https://www.coursesu.com/p/soda-coca-cola-original---bouteille-175l/5192990.html',
                   'description': 'Soda COCA-COLA Original - Bouteille 1,75L',
                   'ean': '5000112611861',
                   'image': './assets/5000112611861.jpg',
                   'leclerc_queries': ['Cola 1.75 L',
                                       'Cola Soda 1.75 L',
                                       'Cola Soda Goût 1.75 L',
                                       'Soda Goût 1.75 L',
                                       'Cola Goût 1.75 L',
                                       'Cola Soda COCA Original Bouteille 1,75 L',
                                       'Soda au Cola Goût Original COCA-COLA',
                                       'Soda COCA-COLA Original - Bouteille 1,75L',
                                       '5000112611861'],
                   'leclerc_query': 'Cola 1.75 L',
                   'name': 'Soda COCA-COLA Original - Bouteille 1,75L',
                   'negatives': {'intermarche': ['sans sucre',
                                                 'vanille',
                                                 'light',
                                                 'zero',
                                                 'cherry',
                                                 '2.25l',
                                                 '1.25l',
                                                 'zéro',
                                                 'caffeine',
                                                 'caféine',
                                                 'promo',
                                                 'lot',
                                                 'x2',
                                                 'x3',
                                                 'mega'],
                                 'leclerc': ['sans sucre',
                                             'vanille',
                                             'light',
                                             'zero',
                                             'cherry',
                                             '2.25l',
                                             '1.25l',
                                             'citron',
                                             'framboise',
                                             'pomme',
                                             'orange',
                                             'zéro',
                                             'caffeine',
                                             'caféine',
                                             'lot',
                                             'duo',
                                             'family',
                                             'ecopack'],
                                 'monoprix': ['sans sucre',
                                              'vanille',
                                              'light',
                                              'zero',
                                              'cherry',
                                              '2.25l',
                                              '1.25l',
                                              'citron',
                                              'framboise',
                                              'pomme',
                                              'orange',
                                              'zéro',
                                              'caffeine',
                                              'caféine',
                                              'promo',
                                              'lot',
                                              'eco',
                                              'maxi',
                                              'format']},
                   'note': '2025-10-31T13:07:56Z · Super U Eysines',
                   'nutriscore_grade': 'unknown',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-unknown.svg',
                   'primary_keywords': ['Cola 1.75 L'],
                   'quantity': '1,75  L',
                   'queries': {'intermarche': ['coca-cola 1,75l',
                                               'coca cola 1,75l',
                                               'coca-cola extraits 1,75l',
                                               'coca cola extraits 1,75l',
                                               'coca-cola original 1,75l'],
                               'leclerc': ['coca-cola extraits 1,75l',
                                           'coca-cola extraits 175cl',
                                           'coca-cola 1,75l',
                                           'coca-cola 175cl',
                                           'coca-cola original'],
                               'monoprix': ['coca-cola extraits',
                                            'coca-cola 1,75l',
                                            'coca-cola 175cl',
                                            'coca-cola extraits 1,75l',
                                            'coca-cola extraits 175cl'],
                               'casino': ['coca cola 1,75l',
                                          'coca cola original 1.75',
                                          'soda coca 1,75l']},
                   'removed': False,
                   'secondary_keywords': ['Goût', 'Original', 'COCA', 'Bouteille', '1.75 L'],
                   'seed_primary_name': 'Soda au Cola Goût Original COCA-COLA',
                   'seed_primary_quantity': '1,75 L',
                   'seed_query': 'Cola Soda COCA Original Bouteille 1,75 L',
                   'source': 'courseu'},
 '5010029229110': {'ean': '5010029229110',
                   'leclerc_queries': ['5010029229110'],
                   'leclerc_query': '5010029229110',
                   'primary_keywords': ['5010029229110'],
                   'removed': True,
                   'source': 'auto'},
 '5411188103387': {'brand': 'Alpro',
                   'description': 'Dessert végétal soja vanille ALPRO - 500g',
                   'ean': '5411188103387',
                   'image': './assets/5411188103387.jpg',
                   'leclerc_queries': ['Alpro 500 G',
                                       'Alpro Dessert 500 G',
                                       'Alpro Dessert végétal 500 G',
                                       'Dessert végétal 500 G',
                                       'Alpro végétal 500 G',
                                       'Alpro Dessert végétal soja vanille 500 g',
                                       'Dessert végétal soja vanille ALPRO',
                                       'Dessert végétal soja vanille ALPRO - 500g',
                                       '5411188103387'],
                   'leclerc_query': 'Alpro 500 G',
                   'name': 'Dessert végétal soja vanille ALPRO - 500g',
                   'note': '2025-10-31T15:36:51Z · Super U Eysines',
                   'nutriscore_grade': 'unknown',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-unknown.svg',
                   'primary_keywords': ['Alpro 500 G'],
                   'quantity': '500  g',
                   'secondary_keywords': ['végétal', 'soja', 'vanille', '500 G'],
                   'seed_primary_name': 'Dessert végétal soja vanille ALPRO',
                   'seed_primary_quantity': '500 G',
                   'seed_query': 'Alpro Dessert végétal soja vanille 500 g',
                   'source': 'courseu'},
 '5411188114536': {'brand': 'Alpro',
                   'description': 'Dessert végétal soja fraise ALPRO - 500g',
                   'ean': '5411188114536',
                   'image': './assets/5411188114536.jpg',
                   'leclerc_queries': ['Alpro fraise 500 G',
                                       'Alpro dessert fraise 500 G',
                                       'Alpro dessert végétal 500 G',
                                       'Dessert végétal 500 G',
                                       'Alpro végétal 500 G',
                                       'Alpro dessert végétal soja fraise 500 g',
                                       'Dessert végétal soja fraise ALPRO',
                                       'Dessert végétal soja fraise ALPRO - 500g',
                                       '5411188114536'],
                   'leclerc_query': 'Alpro fraise 500 G',
                   'name': 'Dessert végétal soja fraise ALPRO - 500g',
                   'note': '2025-11-02T15:09:02Z · Super U Eysines',
                   'nutriscore_grade': 'e',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-e.svg',
                   'primary_keywords': ['Alpro fraise 500 G'],
                   'quantity': '500  g',
                   'queries': {'intermarche': ['Alpro dessert fraise 500 g',
                                               'Dessert végétal soja fraise'],
                               'monoprix': ['Alpro fraise', 'Alpro dessert'],
                               'casino': ['alpro fraise 500g',
                                          'dessert vegetal fraise',
                                          'alpro dessert 500g']},
                   'removed': False,
                   'secondary_keywords': ['végétal',
                                          'soja',
                                          'fraise',
                                          'ALPRO',
                                          '500 G'],
                   'seed_primary_name': 'Dessert végétal soja fraise ALPRO',
                   'seed_primary_quantity': '500 G',
                   'seed_query': 'Alpro Dessert végétal soja fraise 500 g',
                   'source': 'courseu'},
 '5411188118961': {'brand': 'Alpro',
                   'categories': 'Pflanzliche Lebensmittel und Getränke, Fermentierte '
                                 'Lebensmittel, en:Dairy substitutes, Desserts, en:Vegan products, '
                                 'Milchfreie Nachtische, Fermentierte Lebensmittel ohne Milch, '
                                 'Pflanzenbasierte Joghurts, Sojajoghurt, Einfacher Soja-Joghurt',
                   'description': "Dessert végétal soja nature à l'amande ALPRO - 500g",
                   'ean': '5411188118961',
                   'ecoscore_grade': 'a',
                   'ecoscore_image': 'https://static.openfoodfacts.org/images/attributes/ecoscore-a.svg',
                   'image': './assets/5411188118961.jpg',
                   'leclerc_queries': ['Alpro 500 G',
                                       'Alpro Dessert 500 G',
                                       'Alpro Dessert végétal 500 G',
                                       'Dessert végétal 500 G',
                                       'Alpro végétal 500 G',
                                       "Alpro Dessert végétal soja nature l'amande 500 g",
                                       "Dessert végétal soja nature à l'amande ALPRO",
                                       "Dessert végétal soja nature à l'amande ALPRO - 500g",
                                       '5411188118961'],
                   'leclerc_query': 'Alpro 500 G',
                   'name': "Dessert végétal soja nature à l'amande ALPRO - 500g",
                   'negatives': {'monoprix': ['vanille',
                                              'coco',
                                              'noix de coco',
                                              'fraise',
                                              'myrtille']},
                   'note': '2025-10-31T15:29:31Z · Super U Eysines',
                   'nova_group': None,
                   'nutriscore_grade': 'a',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-a.svg',
                   'primary_keywords': ['Alpro 500 G'],
                   'quantity': '500  g',
                   'queries': {'monoprix': ['Alpro amande', 'Dessert amande Alpro'],
                               'casino': ['alpro amande 500g',
                                          'alpro dessert amande',
                                          'dessert vegetal amande']},
                   'removed': False,
                   'secondary_keywords': ['végétal', 'soja', 'nature', 'amande', '500 G'],
                   'seed_primary_name': "Dessert végétal soja nature à l'amande ALPRO",
                   'seed_primary_quantity': '500 G',
                   'seed_query': "Alpro Dessert végétal soja nature l'amande 500 g",
                   'source': 'courseu',
                   'variant': 'amande'},
 '5449000000996': {'ean': '5449000000996',
                   'leclerc_queries': ['5449000000996'],
                   'leclerc_query': '5449000000996',
                   'primary_keywords': ['5449000000996'],
                   'removed': True,
                   'source': 'auto'},
 '8712100731822': {'brand': 'Savora',
                   'canonical': {'brand': 'Savora',
                                 'ean': '8712100731822',
                                 'features': [],
                                 'flavor_color': None,
                                 'form': None,
                                 'images': ['./assets/8712100731822.jpg',
                                            'https://media.carrefour.fr/medias/852e37fd05f24a1c9976e1fe51150cc4/p_540x540/08 '
                                            '712100731822_H1N1_s06.png',
                                            'https://cdn.auchan.fr/media/A0220141215000569861PRIMARY_1200x1200/B2CD/'],
                                 'line': None,
                                 'name_core': 'Moutarde aux aromates SAVORA',
                                 'normalized_signature': '8712100731822 savora moutarde aux '
                                                         'aromates savora 385.0g',
                                 'pack_count': None,
                                 'size_unit': 'g',
                                 'size_value': 385.0,
                                 'variant': None},
                   'categories': 'Condiments, Sauces, Moutardes, en:groceries, Spécialité à la '
                                 'Moutarde',
                   'courseu_slug': '/p/moutarde-savora-n4-amora-bocal-de-385g/7591393.html',
                   'courseu_url': 'https://www.coursesu.com/p/moutarde-savora-n4-amora-bocal-de-385g/7591393.html',
                   'description': 'Moutarde aux aromates SAVORA 385 g',
                   'ean': '8712100731822',
                   'ecoscore_grade': 'b',
                   'ecoscore_image': 'https://static.openfoodfacts.org/images/attributes/ecoscore-b.svg',
                   'image': './assets/8712100731822.jpg',
                   'leclerc_queries': ['Savora 385 G',
                                       'Savora Moutarde 385 G',
                                       'Savora Moutarde Epices 385 G',
                                       'Moutarde Epices 385 G',
                                       'Savora Epices 385 G',
                                       'Savora Moutarde aromates g 385 g',
                                       'Moutarde Epices & Amorates Savora AMORA',
                                       'Moutarde aux aromates SAVORA 385 g',
                                       '8712100731822'],
                   'leclerc_query': 'Savora 385 G',
                   'name': 'Moutarde aux aromates SAVORA 385 g',
                   'negatives': {'intermarche': ['cherry',
                                                 'light',
                                                 'vanille',
                                                 'sans sucre',
                                                 'zero',
                                                 '385.5g',
                                                 '384.5g',
                                                 'douce',
                                                 'bio',
                                                 'x2',
                                                 'lot',
                                                 'format',
                                                 'promo',
                                                 'x3',
                                                 'mega'],
                                 'leclerc': ['cherry',
                                             'light',
                                             'vanille',
                                             'sans sucre',
                                             'zero',
                                             '385.5g',
                                             '384.5g',
                                             'douce',
                                             'bio',
                                             'x2',
                                             'lot',
                                             'format',
                                             'duo',
                                             'family',
                                             'ecopack'],
                                 'monoprix': ['cherry',
                                              'light',
                                              'vanille',
                                              'sans sucre',
                                              'zero',
                                              '385.5g',
                                              '384.5g',
                                              'douce',
                                              'bio',
                                              'x2',
                                              'lot',
                                              'format',
                                              'promo',
                                              'eco',
                                              'maxi']},
                   'note': 'Chronodrive Le Haillan',
                   'nova_group': '3',
                   'nutriscore_grade': 'e',
                   'nutriscore_image': '../assets/nutriscore/nutriscore-e.svg',
                   'primary_keywords': ['Savora 385 G'],
                   'quantity': '385  g',
                   'queries': {'intermarche': ['savora 385g', 'savora moutarde 385g'],
                               'leclerc': ['savora moutarde', 'savora 385g'],
                               'monoprix': ['savora moutarde', 'savora moutarde 385g'],
                               'casino': ['savora 385g',
                                          'moutarde savora',
                                          'savora aromates']},
                   'removed': False,
                   'secondary_keywords': ['Epices', 'Amorates', 'AMORA', 'aromates', '385 G'],
                   'seed_primary_name': 'Moutarde Epices & Amorates Savora AMORA',
                   'seed_primary_quantity': '385 G',
                   'seed_query': 'Savora Moutarde aromates g 385 g',
                   'source': 'chronodrive'}}


def get_seed(ean: str):
    """Return the seed descriptor for the given EAN (string or int)."""
    key = str(ean).strip()
    if not key:
        return None
    return SEED_CATALOG.get(key)


def all_seeds():
    """Return the full seed catalog."""
    return SEED_CATALOG
